// Photo data configuration - Lisa can easily update this file with her own photos and prices
export interface Photo {
  id: number
  title: string // ← THIS IS THE PHOTO NAME/TITLE
  category: string
  price: number // Base price for 5x7
  image: string
  description?: string
  isFeatured?: boolean
  isBestseller: boolean
  purchaseCount: number
  dimensions?: {
    small: { size: string; price: number }
    medium: { size: string; price: number }
    large: { size: string; price: number }
    extraLarge: { size: string; price: number }
  }
  tags?: string[]
}

// Update the categories array to match the user's specified categories
export const categories = [
  "Old Buildings",
  "Animals",
  "Old Buildings at Night",
  "Nature & Sky",
  "Old Elevators in AB",
  "Old Cars & Trains",
]

// Lisa's Complete Photo Collection - 60 photos organized by category
export const photos: Photo[] = [
  // Old Buildings During the Day (1-25)
  {
    id: 1,
    title: "Rustic Red",
    category: "Old Buildings",
    price: 10.0,
    // ⬇️ PASTE YOUR ACTUAL IMAGE URL HERE - make sure it's a direct link ending in .jpg
    image: "https://i.imgur.com/tQQpdqI.jpg",
    description: "A classic red barn surrounded by the Alberta prairies.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Old barn", "prairie", "heritage", "alberta"],
  },
  {
    id: 2,
    title: "Rural Relic",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/4jbrEBS.jpg",
    description: "A weathered farmhouse telling stories of Alberta's agricultural past.",
    isFeatured: false,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["farmhouse", "abandoned", "rural", "heritage"],
  },
  {
    id: 3,
    title: "Open Welcomes",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/4mh5HtB.jpg",
    description: "A beautiful old barn with open doors welcoming all.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "open doors", "heritage", "architecture"],
  },
  {
    id: 4,
    title: "Weathered Remanents",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/dQ53gpn.jpg",
    description: "A old weatherd barn house surrounded by the praries.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn House", "Canola", "pioneer", "heritage"],
  },
  {
    id: 5,
    title: "Old Walls New Winds",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/CAUGdOH.jpg",
    description: "A rustic barn encapsulated by windmills.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["barn", "weathered", "rustic", "Windmills"],
  },
  {
    id: 6,
    title: "Forgotten Shelter",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/QztJPxb.jpg",
    description: "A small farmhouse with missing walls showing off the inside.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Farmhouse", "Olf", "pioneer", "Praries"],
  },
  {
    id: 7,
    title: "Standing Tall",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/ug3L94G.jpg",
    description: "A historic building that kept its shape and structure throughout the passing time.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["House", "Old", "Standing tall", "heritage"],
  },
  {
    id: 8,
    title: "Legacy Remains",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/A8HuuTs.jpg",
    description: "The foundation and stories remain of a single homestead.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["foundation", "ruins", "homestead"],
  },
  {
    id: 9,
    title: "Echoes of the past",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/7ffcq1h.jpg",
    description: "An old country house thats being taken over by new life.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["house", "country", "Trees", "rural"],
  },
  {
    id: 10,
    title: "Crimson Roof",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/VUSqC01.jpg",
    description: "A colourful old house backed by the beautiful sky.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Colourful", "homestead", "sky"],
  },
  {
    id: 11,
    title: "Rustic Serenity",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/ESCe7Dv.jpg",
    description: "The remains of an old barn surrounded by the greenary of trees.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "trees", "trade", "heritage"],
  },
  {
    id: 12,
    title: "Fallen stories",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/vKGR5u5.jpg",
    description: "A vintage barn that has since been collapsed.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "infrastructure", "vintage", "prairie"],
  },
  {
    id: 13,
    title: "Rual Haven",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/8Yc6WEF.jpg",
    description: "An old homestead standing alone amongst the prairies and trees.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["homestea", "Trees", "Prarie"],
  },
  {
    id: 14,
    title: "Golden Dweling",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/OB6BXZx.jpg",
    description: "An old barn standing in a field of canola.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "Conola", "prarie", "Farm"],
  },
  {
    id: 15,
    title: "Forgotten Farm",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/EkYUuGi.jpg",
    description: "A barn that has been left and is starting to colapse in on itself",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Farm", "Barn", "Collapsing", "Forgotten"],
  },
  {
    id: 16,
    title: "Faded Glory",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/uwumzWV.jpg",
    description: "A wheatherd barn that has countinued to stand tall in the Alberta Praries",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "agriculture", "Praries", "sky"],
  },
  {
    id: 17,
    title: "Collapsed Roots",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/KPG7kJf.jpg",
    description: "An old homestead that has fallen in the praries during golden hour.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Homestead", "Golden Hour", "Praries", "classic"],
  },
  {
    id: 18,
    title: "Ghost of Mossleigh",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/gd1Lzxr.jpg",
    description: "A wooden homestead that stands tall on the corner of Mossleigh.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Homestead", "wooden", "Mossleigh", "vintage"],
  },
  {
    id: 19,
    title: "Built to Withstand",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/TR5XH4j.jpg",
    description: "An old brick building standing tall with an overlay of snow around it.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["brick", "snow", "standing", "classic"],
  },
  {
    id: 20,
    title: "Facing the Range",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/ZtsdRAc.jpg",
    description: "An old farm set up surrounded by snow with a beautiful backdrop of mountins.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["farm", "Mountins", "Snow", "Sustained"],
  },
  {
    id: 21,
    title: "Hilltop Haven",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/yQP4ySY.jpg",
    description: "The reminantse of a forgotten homestead sitting atop a hill.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Fallen", "Hilltop", "Homestead", "prairie"],
  },
  {
    id: 22,
    title: "Snowbound Shelter",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/zvLl9c0.jpg",
    description: "An old homestead in the middle of the praries.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Snowy", "Homestead", "Prarie", "Cows"],
  },
  {
    id: 23,
    title: "Rustic Collapse",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/hr77GTm.jpg",
    description: "A beautiful collapsing red barn in a golden feild",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["countryside", "Barn", "Abandoned", "Heritage"],
  },
  {
    id: 24,
    title: "Frozen Haritage",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/h3gjwvd.jpg",
    description: "An old barn standing resilient in a snowy landscape.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Winter", "Barn", "Landscape", "countryside"],
  },
  {
    id: 25,
    title: "Aging Abode",
    category: "Old Buildings",
    price: 10.0,
    image: "https://i.imgur.com/fmAs916.jpg",
    description: "An old wheatherd wooden house standing quietly in a golden feild.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["old homestead", "decay", "countryside", "rustic"],
  },

  // Animals (26-30)
  {
    id: 26,
    title: "Silent Witness",
    category: "Animals",
    price: 10.0,
    image: "https://i.imgur.com/yzCdvxa.jpg",
    description: "A wild fox captured in its natural prairie habitat.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["fox", "prairie", "wild", "habitat"],
  },
  {
    id: 27,
    title: "Bonded",
    category: "Animals",
    price: 10.0,
    image: "https://i.imgur.com/HvNzN2u.jpg",
    description: "A Mother cow with her baby calf in the pasture.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["cow", "family", "pasture", "calf"],
  },
  {
    id: 28,
    title: "Herons Pearch",
    category: "Animals",
    price: 10.0,
    image: "https://i.imgur.com/Xe9ejLA.jpg",
    description: "A graceful blue heron pearched on her tree.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["bird", "blue heron", "graceful", "tree"],
  },
  {
    id: 29,
    title: "Sky born silence",
    category: "Animals",
    price: 10.0,
    image: "https://i.imgur.com/UiC51Vw.jpg",
    description: "An intimate portrait of a blue heron soaring the skies.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Blue heron", "portrait", "sky", "intimate"],
  },
  {
    id: 30,
    title: "Heron Haven",
    category: "Animals",
    price: 10.0,
    image: "https://i.imgur.com/dZIe0zw.jpg",
    description: "A collection of the herons in the rookery.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["heron", "rookery", "patient", "nests"],
  },

  // Old Buildings at Night (31-41) - UPDATED SECTION
  {
    id: 31,
    title: "Winter Collapse",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/aH3yYaf.jpg",
    description: "A partially collapsed house surrounded by snow under a moody winter sky.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["barn", "moonlight", "night", "prairie"],
  },
  {
    id: 32,
    title: "Winter Shadows",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/lnKOmD5.jpg",
    description: "A dark weathered sky standing alone in a snowy field under a misty sky.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "Misty", "Snow", "Decay"],
  },
  {
    id: 33,
    title: "Evening glow",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/B8aNfZJ.jpg",
    description: "A rustic barn sillhouetted against a vibrant golden sunset.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["barn", "sunset", "silhouette", "magical"],
  },
  {
    id: 34,
    title: "Before the storm",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/IvZsHJf.jpg",
    description: "The rustic charm of a weathered barn set against a moody sky before the storm.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Barn", "Storm", "Dramatic", "Rual"],
  },
  {
    id: 35,
    title: "The Ghostly feeling of Mossliegh I",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/Zo1hYF4.jpg",
    description: "The House on the mossliegh corner light up by lights during the night.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Series", "Lit from within", "dramatic", "abandoned"],
  },
  {
    id: 36,
    title: "The Ghostly feeling of Mossliegh II",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/KNIouJH.jpg",
    description: "The House on the mossliegh corner light up by lights during the night.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Series", "Lit from within", "dramatic", "abandoned"],
  },
  {
    id: 37,
    title: "The Ghostly feeling of Mossliegh III",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/uern2C1.jpg",
    description: "The House on the mossliegh corner light up by lights during the night.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Series", "Lit from within", "dramatic", "abandoned"],
  },
  {
    id: 38,
    title: "The Ghostly feeling of Mossliegh IV",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/dEXufsG.jpg",
    description: "The House on the mossliegh corner light up by lights during the night.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Series", "Lit from within", "dramatic", "abandoned"],
  },
  {
    id: 39,
    title: "The Ghostly feeling of Mossliegh V",
    category: "Old Buildings at Night",
    price: 10.0,
    image: "https://i.imgur.com/kbw919d.jpg",
    description: "The House on the mossliegh corner light up by lights during the night.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Series", "Lit from within", "dramatic", "abandoned"],
  },

  // Nature/Sky Photos (42-50)
  {
    id: 43,
    title: "Whispers of Frost",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/iN6EokD.jpg",
    description: "The beautiful hoar frost settiling on a branch",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Hoar Frost", "Winter", "Branch", "alberta"],
  },
  {
    id: 44,
    title: "Frost Holds Still",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/0XKz3MT.jpg",
    description: "An abandoned prairie house beneath a hoarfrost laced tree.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Abandoned", "Frost", "quiet", "Homestead"],
  },
  {
    id: 45,
    title: "Echos in Ice",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/hslbM9a.jpg",
    description: "A dramatic frozen waterfall covered in snow.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Waterfall", "Frozen", "dramatic", "Winter"],
  },
  {
    id: 46,
    title: "Days Farewell",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/eEXPp12.jpg",
    description: "A stunning prarie sunset breaking through the clouds",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Sunset", "Clouds", "Prarie"],
  },
  {
    id: 47,
    title: "Mirrored Stillness",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/Fm4mKmY.jpg",
    description: "A beautiful mirrored treeline reflecting in the water.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Water", "Trees", "Fall", "textured"],
  },
  {
    id: 48,
    title: "Painted Skies",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/okYSd7U.jpg",
    description: "stunning dancing aroura in the alberta praries.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["aroura", "dancing", "praire", "painted"],
  },
  {
    id: 49,
    title: "Nights Lantern",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/6itqO2n.jpg",
    description: "A beautiful portrait of a full moon.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Moon", "Full", "Praries", "glow"],
  },
  {
    id: 50,
    title: "Lights above Labour",
    category: "Nature & Sky",
    price: 10.0,
    image: "https://i.imgur.com/XRhWtKI.jpg",
    description: "The stunning aroura pictured over an irrigation wheel.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Aroura", "Irrigation", "Dancing", "night"],
  },

  // Old Elevators in Alberta (51-55)
  {
    id: 51,
    title: "Sharples at Sunset",
    category: "Old Elevators in AB",
    price: 10.0,
    image: "https://i.imgur.com/rKCrVUX.jpg",
    description: "The iconic grain elevator in Sharples, Alberta.",
    isFeatured: true,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["sharples", "elevator", "iconic", "alberta"],
  },
  {
    id: 52,
    title: "Summerview Elevator",
    category: "Old Elevators in AB",
    price: 10.0,
    image: "https://i.imgur.com/7xdHfBf.jpg",
    description: "The historic grain elevator in Summerview, Alberta.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["summerview", "elevator", "historic", "grain"],
  },
  {
    id: 53,
    title: "Harvest and Horizon",
    category: "Old Elevators in AB",
    price: 10.0,
    image: "https://i.imgur.com/hKL0DYh.jpg",
    description: "A well-preserved elevator with picturesque mountains.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["mountains", "elevator", "preserved", "alberta"],
  },
  {
    id: 54,
    title: "Esther Elevator",
    category: "Old Elevators in AB",
    price: 10.0,
    image: "https://i.imgur.com/vJx5LfV.jpg",
    description: "The stately grain elevator in Esther, Alberta.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Esther", "elevator", "stately", "grain"],
  },
  {
    id: 55,
    title: "Warwick Elevator",
    category: "Old Elevators in AB",
    price: 10.0,
    image: "https://i.imgur.com/YfsC3Ev.jpg",
    description: "A classic prairie elevator in Warwick, Alberta.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Warwick", "elevator", "classic", "prairie"],
  },

  // Old Cars and Trains (56-59)
  {
    id: 56,
    title: "Miles Behind",
    category: "Old Cars & Trains",
    price: 10.0,
    image: "https://i.imgur.com/vJOOe5n.jpg",
    description: "A weathered vintage car on the prairie.",
    isFeatured: false,
    isBestseller: false,
    purchaseCount: 0,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["car", "vintage", "weathered", "prairie"],
  },
  {
    id: 57,
    title: "Rails Through Fire",
    category: "Old Cars & Trains",
    price: 10.0,
    image: "https://i.imgur.com/X7vmGsj.jpg",
    description: "A majestic steam locomotive from Alberta's railway heritage at Murants Curve.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["steam locomotive", "majestic", "railway", "heritage"],
  },
  {
    id: 58,
    title: "Snowbound Package",
    category: "Old Cars & Trains",
    price: 10.0,
    image: "https://i.imgur.com/WBBaeRj.jpg",
    description: "The beautiful Train coming around murants curve in the winter.",
    purchaseCount: 0,
    isBestseller: false,
    dimensions: {
      small: { size: "5×7 in", price: 10.0 },
      medium: { size: "8×11 in", price: 15.0 },
      large: { size: "11×14 in", price: 25.0 },
      extraLarge: { size: "16×20 in", price: 45.0 },
    },
    tags: ["Murants Curve", "Winter", "Train", "heritage"],
  },
]

// Bestseller threshold - items become bestsellers after 10 purchases
const BESTSELLER_THRESHOLD = 10

// Function to handle a purchase and update bestseller status
export const handlePurchase = (photoId: number) => {
  const photo = photos.find((p) => p.id === photoId)
  if (photo) {
    photo.purchaseCount += 1
    if (photo.purchaseCount >= BESTSELLER_THRESHOLD) {
      photo.isBestseller = true
    }
    // In a real app, this would save to a database
    // For now, we could save to localStorage
    if (typeof window !== "undefined") {
      localStorage.setItem("photoData", JSON.stringify(photos))
    }
  }
}

// Function to load purchase data from localStorage on app start
export const loadPurchaseData = () => {
  if (typeof window !== "undefined") {
    const savedData = localStorage.getItem("photoData")
    if (savedData) {
      const savedPhotos = JSON.parse(savedData)
      savedPhotos.forEach((savedPhoto: Photo) => {
        const photo = photos.find((p) => p.id === savedPhoto.id)
        if (photo) {
          photo.purchaseCount = savedPhoto.purchaseCount || 0
          photo.isBestseller = savedPhoto.purchaseCount >= BESTSELLER_THRESHOLD
        }
      })
    }
  }
}

// Helper functions
export const getFeaturedPhotos = () => photos.filter((photo) => photo.isFeatured)
export const getPhotosByCategory = (category: string) => photos.filter((photo) => photo.category === category)
export const getPhotoById = (id: number) => photos.find((photo) => photo.id === id)
export const getBestsellers = () => photos.filter((photo) => photo.isBestseller)
