// Shipping calculator based on distance zones similar to Canada Post
// Base location: Strathmore, AB (T1P)

interface ShippingZone {
  name: string
  description: string
  price: number
  deliveryDays: string
}

// Postal code prefixes and their shipping zones
const POSTAL_CODE_ZONES: { [key: string]: ShippingZone } = {
  // LOCAL ZONE - Free delivery within 50km of Strathmore
  T1P: { name: "Local", description: "Strathmore area", price: 0, deliveryDays: "1-2 days" },
  T1X: { name: "Local", description: "Chestermere area", price: 0, deliveryDays: "1-2 days" },
  T0J: { name: "Local", description: "Rural Strathmore area", price: 0, deliveryDays: "1-2 days" },

  // CALGARY METRO - Free delivery
  T1A: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1B: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1C: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1E: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1G: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1H: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1J: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1K: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1L: { name: "Calgary Metro", description: "Calgary SE", price: 0, deliveryDays: "1-2 days" },
  T1M: { name: "Calgary Metro", description: "Calgary NE", price: 0, deliveryDays: "1-2 days" },
  T1N: { name: "Calgary Metro", description: "Calgary NE", price: 0, deliveryDays: "1-2 days" },
  T1P: { name: "Calgary Metro", description: "Calgary NE", price: 0, deliveryDays: "1-2 days" },
  T1R: { name: "Calgary Metro", description: "Calgary NE", price: 0, deliveryDays: "1-2 days" },
  T1S: { name: "Calgary Metro", description: "Calgary NE", price: 0, deliveryDays: "1-2 days" },
  T1V: { name: "Calgary Metro", description: "Calgary NE", price: 0, deliveryDays: "1-2 days" },
  T1W: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T1Y: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T2A: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T2B: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T2C: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T2E: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T2G: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2H: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2J: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2K: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2L: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2M: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2N: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2P: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2R: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2S: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2T: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2V: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2W: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2X: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2Y: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T2Z: { name: "Calgary Metro", description: "Calgary SW", price: 0, deliveryDays: "1-2 days" },
  T3A: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3B: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3C: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3E: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3G: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3H: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3J: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3K: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3L: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3M: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3N: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3P: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3R: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3S: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },
  T3Z: { name: "Calgary Metro", description: "Calgary NW", price: 0, deliveryDays: "1-2 days" },

  // NEARBY COMMUNITIES - Free delivery
  T4C: { name: "Nearby", description: "Cochrane area", price: 0, deliveryDays: "1-2 days" },
  T4A: { name: "Nearby", description: "Airdrie area", price: 0, deliveryDays: "1-2 days" },
  T0L: { name: "Nearby", description: "Okotoks area", price: 0, deliveryDays: "1-2 days" },
  T1S: { name: "Nearby", description: "High River area", price: 0, deliveryDays: "1-2 days" },

  // ALBERTA REGIONAL - $12.99
  T0A: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0B: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0C: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0E: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0G: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0H: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0K: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T0M: { name: "Alberta Regional", description: "Central Alberta", price: 12.99, deliveryDays: "2-4 days" },
  T4E: { name: "Alberta Regional", description: "Red Deer area", price: 12.99, deliveryDays: "2-4 days" },
  T4N: { name: "Alberta Regional", description: "Red Deer area", price: 12.99, deliveryDays: "2-4 days" },
  T4P: { name: "Alberta Regional", description: "Red Deer area", price: 12.99, deliveryDays: "2-4 days" },
  T4R: { name: "Alberta Regional", description: "Red Deer area", price: 12.99, deliveryDays: "2-4 days" },
  T4S: { name: "Alberta Regional", description: "Red Deer area", price: 12.99, deliveryDays: "2-4 days" },
  T5A: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5B: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5C: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5E: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5G: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5H: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5J: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5K: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5L: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5M: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5N: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5P: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5R: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5S: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5T: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5V: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5W: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5X: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5Y: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T5Z: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6A: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6B: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6C: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6E: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6G: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6H: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6J: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6K: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6L: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6M: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6N: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6P: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6R: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6S: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6T: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6V: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6W: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },
  T6X: { name: "Alberta Regional", description: "Edmonton area", price: 12.99, deliveryDays: "2-4 days" },

  // WESTERN CANADA - $16.99
  V0A: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0B: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0C: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0E: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0G: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0H: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0J: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0K: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0L: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0M: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0N: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0P: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0R: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0S: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0T: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0V: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0W: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V0X: { name: "Western Canada", description: "BC Interior", price: 16.99, deliveryDays: "3-5 days" },
  V1A: { name: "Western Canada", description: "Kamloops area", price: 16.99, deliveryDays: "3-5 days" },
  V1B: { name: "Western Canada", description: "Kamloops area", price: 16.99, deliveryDays: "3-5 days" },
  V1C: { name: "Western Canada", description: "Kamloops area", price: 16.99, deliveryDays: "3-5 days" },
  V1E: { name: "Western Canada", description: "Kamloops area", price: 16.99, deliveryDays: "3-5 days" },
  V1G: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1H: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1J: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1K: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1L: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1M: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1N: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1P: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1R: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1S: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1T: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1V: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1W: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1X: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1Y: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V1Z: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2A: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2B: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2C: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2E: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2G: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2H: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2J: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2K: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2L: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2M: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2N: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2P: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2R: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2S: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2T: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2V: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2W: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2X: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2Y: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V2Z: { name: "Western Canada", description: "Prince George area", price: 16.99, deliveryDays: "3-5 days" },
  V3A: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3B: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3C: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3E: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3G: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3H: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3J: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3K: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3L: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3M: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3N: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3P: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3R: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3S: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3T: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3V: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3W: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3X: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3Y: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V3Z: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4A: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4B: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4C: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4E: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4G: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4H: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4J: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4K: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4L: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4M: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4N: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4P: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4R: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4S: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4T: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4V: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4W: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V4X: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V5A: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5B: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5C: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5E: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5G: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5H: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5J: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5K: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5L: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5M: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5N: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5P: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5R: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5S: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5T: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5V: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5W: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5X: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5Y: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V5Z: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6A: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6B: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6C: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6E: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6G: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6H: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6J: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6K: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6L: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6M: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6N: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6P: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6R: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6S: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6T: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6V: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6W: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6X: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6Y: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V6Z: { name: "Western Canada", description: "Vancouver", price: 16.99, deliveryDays: "3-5 days" },
  V7A: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7B: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7C: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7E: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7G: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7H: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7J: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7K: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7L: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7M: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7N: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7P: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7R: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7S: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7T: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7V: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7W: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7X: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V7Y: { name: "Western Canada", description: "Vancouver Metro", price: 16.99, deliveryDays: "3-5 days" },
  V8A: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8B: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8C: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8G: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8H: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8J: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8K: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8L: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8M: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8N: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8P: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8R: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8S: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8T: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8V: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8W: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8X: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8Y: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V8Z: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9A: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9B: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9C: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9E: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9G: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9H: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9J: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9K: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9L: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9M: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9N: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9P: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9R: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9S: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9T: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9V: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9W: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9X: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9Y: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },
  V9Z: { name: "Western Canada", description: "Victoria area", price: 16.99, deliveryDays: "3-5 days" },

  // SASKATCHEWAN - $14.99
  S0A: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0B: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0C: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0E: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0G: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0H: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0J: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0K: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0L: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0M: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0N: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S0P: { name: "Saskatchewan", description: "Saskatchewan", price: 14.99, deliveryDays: "3-5 days" },
  S4A: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4B: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4C: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4E: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4G: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4H: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4J: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4K: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4L: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4M: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4N: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4P: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4R: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4S: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4T: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4V: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4W: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4X: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4Y: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S4Z: { name: "Saskatchewan", description: "Regina area", price: 14.99, deliveryDays: "3-5 days" },
  S7A: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7B: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7C: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7E: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7G: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7H: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7J: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7K: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7L: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7M: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7N: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7P: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7R: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7S: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7T: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7V: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7W: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },
  S7X: { name: "Saskatchewan", description: "Saskatoon area", price: 14.99, deliveryDays: "3-5 days" },

  // MANITOBA - $18.99
  R0A: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0B: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0C: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0E: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0G: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0H: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0J: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0K: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0L: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0M: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R0N: { name: "Manitoba", description: "Manitoba", price: 18.99, deliveryDays: "4-6 days" },
  R1A: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1B: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1C: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1E: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1G: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1H: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1J: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1K: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1L: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1M: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1N: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1P: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1R: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1S: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1T: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1V: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1W: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1X: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1Y: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R1Z: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2A: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2A: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2B: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2C: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2E: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2G: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2H: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2J: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2K: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2L: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2M: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2N: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2P: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2R: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2S: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2T: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2V: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2W: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2X: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R2Y: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3A: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3B: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3C: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3E: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3G: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3H: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3J: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3K: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3L: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3M: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3N: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3P: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3R: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3S: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3T: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3V: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3W: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3X: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },
  R3Y: { name: "Manitoba", description: "Winnipeg area", price: 18.99, deliveryDays: "4-6 days" },

  // EASTERN CANADA - $22.99
  K0A: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0B: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0C: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0E: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0G: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0H: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0J: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0K: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0L: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K0M: { name: "Eastern Canada", description: "Eastern Ontario", price: 22.99, deliveryDays: "5-7 days" },
  K1A: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1B: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1C: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1E: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1G: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1H: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1J: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1K: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1L: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1M: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1N: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1P: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1R: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1S: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1T: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1V: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1W: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1X: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1Y: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K1Z: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2A: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2B: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2C: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2E: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2G: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2H: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2J: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2K: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2L: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2M: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2P: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2R: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2S: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2T: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2V: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },
  K2W: { name: "Eastern Canada", description: "Ottawa area", price: 22.99, deliveryDays: "5-7 days" },

  // QUEBEC - $24.99
  G0A: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0B: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0C: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0E: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0G: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0H: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0J: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0K: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0L: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0M: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0N: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0P: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0R: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0S: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0T: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0V: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0W: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0X: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0Y: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G0Z: { name: "Quebec", description: "Quebec", price: 24.99, deliveryDays: "5-8 days" },
  G1A: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1B: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1C: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1E: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1G: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1H: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1J: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1K: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1L: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1M: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1N: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1P: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1R: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1S: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1T: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1V: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1W: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1X: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G1Y: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2A: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2B: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2C: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2E: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2G: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2J: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2K: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2L: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2M: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },
  G2N: { name: "Quebec", description: "Quebec City area", price: 24.99, deliveryDays: "5-8 days" },

  // ATLANTIC CANADA - $26.99
  A0A: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0B: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0C: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0E: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0G: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0H: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0J: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0K: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0L: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0M: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0N: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0P: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A0R: { name: "Atlantic Canada", description: "Newfoundland", price: 26.99, deliveryDays: "6-10 days" },
  A1A: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  A1B: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  A1C: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  A1E: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  A1G: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  A1H: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  A1S: { name: "Atlantic Canada", description: "St. Johns area", price: 26.99, deliveryDays: "6-10 days" },
  B0A: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0E: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0H: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0J: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0K: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0L: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0M: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0N: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0P: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0R: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0S: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0T: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0V: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B0W: { name: "Atlantic Canada", description: "Nova Scotia", price: 26.99, deliveryDays: "6-10 days" },
  B1A: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1B: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1C: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1E: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1G: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1H: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1J: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1K: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1L: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1M: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1N: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1P: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1R: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1S: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1T: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1V: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1W: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1X: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B1Y: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2A: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2G: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2H: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2J: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2K: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2L: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2M: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2N: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2P: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2R: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2S: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2T: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2V: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2W: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2X: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2Y: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B2Z: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3A: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3B: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3E: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3G: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3H: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3J: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3K: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3L: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3M: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3N: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3P: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3R: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3S: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3T: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3V: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3W: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3X: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3Y: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B3Z: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4A: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4B: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4C: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4E: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4G: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4H: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4J: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4K: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4L: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4M: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4N: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4P: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4R: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4S: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4T: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4V: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4W: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4X: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4Y: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B4Z: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },
  B5A: { name: "Atlantic Canada", description: "Halifax area", price: 26.99, deliveryDays: "6-10 days" },

  // NEW BRUNSWICK - $24.99
  E0A: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0B: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0C: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0E: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0G: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0H: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0J: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0K: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0L: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0M: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E0N: { name: "Atlantic Canada", description: "New Brunswick", price: 24.99, deliveryDays: "5-8 days" },
  E1A: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },
  E1B: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },
  E1C: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },
  E1E: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },
  E1G: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },
  E1H: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },
  E1J: { name: "Atlantic Canada", description: "Moncton area", price: 24.99, deliveryDays: "5-8 days" },

  // PRINCE EDWARD ISLAND - $24.99
  C0A: { name: "Atlantic Canada", description: "Prince Edward Island", price: 24.99, deliveryDays: "5-8 days" },
  C0B: { name: "Atlantic Canada", description: "Prince Edward Island", price: 24.99, deliveryDays: "5-8 days" },
  C1A: { name: "Atlantic Canada", description: "Charlottetown area", price: 24.99, deliveryDays: "5-8 days" },
  C1B: { name: "Atlantic Canada", description: "Charlottetown area", price: 24.99, deliveryDays: "5-8 days" },
  C1C: { name: "Atlantic Canada", description: "Charlottetown area", price: 24.99, deliveryDays: "5-8 days" },
  C1E: { name: "Atlantic Canada", description: "Charlottetown area", price: 24.99, deliveryDays: "5-8 days" },

  // NORTHERN TERRITORIES - $34.99
  X0A: { name: "Northern Canada", description: "Northwest Territories", price: 34.99, deliveryDays: "7-14 days" },
  X0B: { name: "Northern Canada", description: "Northwest Territories", price: 34.99, deliveryDays: "7-14 days" },
  X0C: { name: "Northern Canada", description: "Northwest Territories", price: 34.99, deliveryDays: "7-14 days" },
  X0E: { name: "Northern Canada", description: "Northwest Territories", price: 34.99, deliveryDays: "7-14 days" },
  X1A: { name: "Northern Canada", description: "Yellowknife area", price: 34.99, deliveryDays: "7-14 days" },
  Y0A: { name: "Northern Canada", description: "Yukon", price: 34.99, deliveryDays: "7-14 days" },
  Y0B: { name: "Northern Canada", description: "Yukon", price: 34.99, deliveryDays: "7-14 days" },
  Y1A: { name: "Northern Canada", description: "Whitehorse area", price: 34.99, deliveryDays: "7-14 days" },
  X0A: { name: "Northern Canada", description: "Nunavut", price: 34.99, deliveryDays: "7-14 days" },
  X0B: { name: "Northern Canada", description: "Nunavut", price: 34.99, deliveryDays: "7-14 days" },
  X0C: { name: "Northern Canada", description: "Nunavut", price: 34.99, deliveryDays: "7-14 days" },
}

// Default shipping zone for unknown postal codes
const DEFAULT_ZONE: ShippingZone = {
  name: "Standard",
  description: "Standard shipping",
  price: 19.99,
  deliveryDays: "5-10 days",
}

export function calculateShippingByPostalCode(
  postalCode: string,
  subtotal = 0,
): {
  zone: ShippingZone
  price: number
  freeShippingEligible: boolean
} {
  if (!postalCode || postalCode.trim().length < 3) {
    return {
      zone: DEFAULT_ZONE,
      price: DEFAULT_ZONE.price,
      freeShippingEligible: false,
    }
  }

  // Clean and format postal code (first 3 characters, uppercase)
  const cleanPostalCode = postalCode.replace(/\s+/g, "").toUpperCase().substring(0, 3)

  // Find matching zone
  const zone = POSTAL_CODE_ZONES[cleanPostalCode] || DEFAULT_ZONE

  // Check for free shipping eligibility
  const freeShippingEligible = subtotal >= 100 || zone.price === 0
  const finalPrice = freeShippingEligible ? 0 : zone.price

  return {
    zone,
    price: finalPrice,
    freeShippingEligible,
  }
}

export function getShippingZoneInfo(postalCode: string): ShippingZone | null {
  if (!postalCode || postalCode.trim().length < 3) {
    return null
  }

  const cleanPostalCode = postalCode.replace(/\s+/g, "").toUpperCase().substring(0, 3)
  return POSTAL_CODE_ZONES[cleanPostalCode] || DEFAULT_ZONE
}

export function isValidCanadianPostalCode(postalCode: string): boolean {
  const canadianPostalCodeRegex = /^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$/
  return canadianPostalCodeRegex.test(postalCode.trim())
}

// Get all available shipping zones for display
export function getAllShippingZones(): { [key: string]: ShippingZone[] } {
  const zones: { [key: string]: ShippingZone[] } = {}

  Object.entries(POSTAL_CODE_ZONES).forEach(([postalCode, zone]) => {
    if (!zones[zone.name]) {
      zones[zone.name] = []
    }

    // Only add unique zones (avoid duplicates)
    const exists = zones[zone.name].some((z) => z.price === zone.price && z.description === zone.description)

    if (!exists) {
      zones[zone.name].push(zone)
    }
  })

  return zones
}
